export interface Country {
    name: string;
    code: string;
    dial: string;
}

export const countries: Country[] = [
    { name: "Afghanistan", code: "AFG", dial: "+93" },
    { name: "Albania", code: "ALB", dial: "+355" },
    { name: "Algeria", code: "DZA", dial: "+213" },
    { name: "American Samoa", code: "ASM", dial: "+1684" },
    { name: "Andorra", code: "AND", dial: "+376" },
    { name: "Angola", code: "AGO", dial: "+244" },
    { name: "Anguilla", code: "AIA", dial: "+1264" },
    { name: "Antarctica", code: "ATA", dial: "+672" },
    { name: "Antigua and Barbuda", code: "ATG", dial: "+1268" },
    { name: "Argentina", code: "ARG", dial: "+54" },
    { name: "Armenia", code: "ARM", dial: "+374" },
    { name: "Aruba", code: "ABW", dial: "+297" },
    { name: "Australia", code: "AUS", dial: "+61" },
    { name: "Austria", code: "AUT", dial: "+43" },
    { name: "Azerbaijan", code: "AZE", dial: "+994" },
    { name: "Bahamas", code: "BHS", dial: "+1242" },
    { name: "Bahrain", code: "BHR", dial: "+973" },
    { name: "Bangladesh", code: "BGD", dial: "+880" },
    { name: "Barbados", code: "BRB", dial: "+1246" },
    { name: "Belarus", code: "BLR", dial: "+375" },
    { name: "Belgium", code: "BEL", dial: "+32" },
    { name: "Belize", code: "BLZ", dial: "+501" },
    { name: "Benin", code: "BEN", dial: "+229" },
    { name: "Bermuda", code: "BMU", dial: "+1441" },
    { name: "Bhutan", code: "BTN", dial: "+975" },
    { name: "Bolivia", code: "BOL", dial: "+591" },
    { name: "Bosnia and Herzegovina", code: "BIH", dial: "+387" },
    { name: "Botswana", code: "BWA", dial: "+267" },
    { name: "Brazil", code: "BRA", dial: "+55" },
    { name: "British Virgin Islands", code: "VGB", dial: "+1284" },
    { name: "Brunei", code: "BRN", dial: "+673" },
    { name: "Bulgaria", code: "BGR", dial: "+359" },
    { name: "Burkina Faso", code: "BFA", dial: "+226" },
    { name: "Burundi", code: "BDI", dial: "+257" },
    { name: "Cambodia", code: "KHM", dial: "+855" },
    { name: "Cameroon", code: "CMR", dial: "+237" },
    { name: "Canada", code: "CAN", dial: "+1" },
    { name: "Cape Verde", code: "CPV", dial: "+238" },
    { name: "Cayman Islands", code: "CYM", dial: "+1345" },
    { name: "Central African Republic", code: "CAF", dial: "+236" },
    { name: "Chad", code: "TCD", dial: "+235" },
    { name: "Chile", code: "CHL", dial: "+56" },
    { name: "China", code: "CHN", dial: "+86" },
    { name: "Christmas Island", code: "CXR", dial: "+61" },
    { name: "Cocos Islands", code: "CCK", dial: "+61" },
    { name: "Colombia", code: "COL", dial: "+57" },
    { name: "Comoros", code: "COM", dial: "+269" },
    { name: "Congo", code: "COG", dial: "+242" },
    { name: "DR Congo", code: "COD", dial: "+243" },
    { name: "Cook Islands", code: "COK", dial: "+682" },
    { name: "Costa Rica", code: "CRI", dial: "+506" },
    { name: "Croatia", code: "HRV", dial: "+385" },
    { name: "Cuba", code: "CUB", dial: "+53" },
    { name: "Curacao", code: "CUW", dial: "+599" },
    { name: "Cyprus", code: "CYP", dial: "+357" },
    { name: "Czech Republic", code: "CZE", dial: "+420" },
    { name: "Denmark", code: "DNK", dial: "+45" },
    { name: "Djibouti", code: "DJI", dial: "+253" },
    { name: "Dominica", code: "DMA", dial: "+1767" },
    { name: "Dominican Republic", code: "DOM", dial: "+1809" },
    { name: "Ecuador", code: "ECU", dial: "+593" },
    { name: "Egypt", code: "EGY", dial: "+20" },
    { name: "El Salvador", code: "SLV", dial: "+503" },
    { name: "Equatorial Guinea", code: "GNQ", dial: "+240" },
    { name: "Eritrea", code: "ERI", dial: "+291" },
    { name: "Estonia", code: "EST", dial: "+372" },
    { name: "Eswatini", code: "SWZ", dial: "+268" },
    { name: "Ethiopia", code: "ETH", dial: "+251" },
    { name: "Falkland Islands", code: "FLK", dial: "+500" },
    { name: "Faroe Islands", code: "FRO", dial: "+298" },
    { name: "Fiji", code: "FJI", dial: "+679" },
    { name: "Finland", code: "FIN", dial: "+358" },
    { name: "France", code: "FRA", dial: "+33" },
    { name: "French Guiana", code: "GUF", dial: "+594" },
    { name: "French Polynesia", code: "PYF", dial: "+689" },
    { name: "Gabon", code: "GAB", dial: "+241" },
    { name: "Gambia", code: "GMB", dial: "+220" },
    { name: "Georgia", code: "GEO", dial: "+995" },
    { name: "Germany", code: "DEU", dial: "+49" },
    { name: "Ghana", code: "GHA", dial: "+233" },
    { name: "Gibraltar", code: "GIB", dial: "+350" },
    { name: "Greece", code: "GRC", dial: "+30" },
    { name: "Greenland", code: "GRL", dial: "+299" },
    { name: "Grenada", code: "GRD", dial: "+1473" },
    { name: "Guadeloupe", code: "GLP", dial: "+590" },
    { name: "Guam", code: "GUM", dial: "+1671" },
    { name: "Guatemala", code: "GTM", dial: "+502" },
    { name: "Guernsey", code: "GGY", dial: "+44" },
    { name: "Guinea", code: "GIN", dial: "+224" },
    { name: "Guinea-Bissau", code: "GNB", dial: "+245" },
    { name: "Guyana", code: "GUY", dial: "+592" },
    { name: "Haiti", code: "HTI", dial: "+509" },
    { name: "Honduras", code: "HND", dial: "+504" },
    { name: "Hong Kong", code: "HKG", dial: "+852" },
    { name: "Hungary", code: "HUN", dial: "+36" },
    { name: "Iceland", code: "ISL", dial: "+354" },
    { name: "India", code: "IND", dial: "+91" },
    { name: "Indonesia", code: "IDN", dial: "+62" },
    { name: "Iran", code: "IRN", dial: "+98" },
    { name: "Iraq", code: "IRQ", dial: "+964" },
    { name: "Ireland", code: "IRL", dial: "+353" },
    { name: "Isle of Man", code: "IMN", dial: "+44" },
    { name: "Israel", code: "ISR", dial: "+972" },
    { name: "Italy", code: "ITA", dial: "+39" },
    { name: "Jamaica", code: "JAM", dial: "+1876" },
    { name: "Japan", code: "JPN", dial: "+81" },
    { name: "Jersey", code: "JEY", dial: "+44" },
    { name: "Jordan", code: "JOR", dial: "+962" },
    { name: "Kazakhstan", code: "KAZ", dial: "+7" },
    { name: "Kenya", code: "KEN", dial: "+254" },
    { name: "Kiribati", code: "KIR", dial: "+686" },
    { name: "Kuwait", code: "KWT", dial: "+965" },
    { name: "Kyrgyzstan", code: "KGZ", dial: "+996" },
    { name: "Laos", code: "LAO", dial: "+856" },
    { name: "Latvia", code: "LVA", dial: "+371" },
    { name: "Lebanon", code: "LBN", dial: "+961" },
    { name: "Lesotho", code: "LSO", dial: "+266" },
    { name: "Liberia", code: "LBR", dial: "+231" },
    { name: "Libya", code: "LBY", dial: "+218" },
    { name: "Liechtenstein", code: "LIE", dial: "+423" },
    { name: "Lithuania", code: "LTU", dial: "+370" },
    { name: "Luxembourg", code: "LUX", dial: "+352" },
    { name: "Macao", code: "MAC", dial: "+853" },
    { name: "Madagascar", code: "MDG", dial: "+261" },
    { name: "Malawi", code: "MWI", dial: "+265" },
    { name: "Malaysia", code: "MYS", dial: "+60" },
    { name: "Maldives", code: "MDV", dial: "+960" },
    { name: "Mali", code: "MLI", dial: "+223" },
    { name: "Malta", code: "MLT", dial: "+356" },
    { name: "Marshall Islands", code: "MHL", dial: "+692" },
    { name: "Martinique", code: "MTQ", dial: "+596" },
    { name: "Mauritania", code: "MRT", dial: "+222" },
    { name: "Mauritius", code: "MUS", dial: "+230" },
    { name: "Mayotte", code: "MYT", dial: "+262" },
    { name: "Mexico", code: "MEX", dial: "+52" },
    { name: "Micronesia", code: "FSM", dial: "+691" },
    { name: "Moldova", code: "MDA", dial: "+373" },
    { name: "Monaco", code: "MCO", dial: "+377" },
    { name: "Mongolia", code: "MNG", dial: "+976" },
    { name: "Montenegro", code: "MNE", dial: "+382" },
    { name: "Montserrat", code: "MSR", dial: "+1664" },
    { name: "Morocco", code: "MAR", dial: "+212" },
    { name: "Mozambique", code: "MOZ", dial: "+258" },
    { name: "Myanmar", code: "MMR", dial: "+95" },
    { name: "Namibia", code: "NAM", dial: "+264" },
    { name: "Nauru", code: "NRU", dial: "+674" },
    { name: "Nepal", code: "NPL", dial: "+977" },
    { name: "Netherlands", code: "NLD", dial: "+31" },
    { name: "New Caledonia", code: "NCL", dial: "+687" },
    { name: "New Zealand", code: "NZL", dial: "+64" },
    { name: "Nicaragua", code: "NIC", dial: "+505" },
    { name: "Niger", code: "NER", dial: "+227" },
    { name: "Nigeria", code: "NGA", dial: "+234" },
    { name: "Niue", code: "NIU", dial: "+683" },
    { name: "North Korea", code: "PRK", dial: "+850" },
    { name: "North Macedonia", code: "MKD", dial: "+389" },
    { name: "Northern Mariana Islands", code: "MNP", dial: "+1670" },
    { name: "Norway", code: "NOR", dial: "+47" },
    { name: "Oman", code: "OMN", dial: "+968" },
    { name: "Pakistan", code: "PAK", dial: "+92" },
    { name: "Palau", code: "PLW", dial: "+680" },
    { name: "Palestine", code: "PSE", dial: "+970" },
    { name: "Panama", code: "PAN", dial: "+507" },
    { name: "Papua New Guinea", code: "PNG", dial: "+675" },
    { name: "Paraguay", code: "PRY", dial: "+595" },
    { name: "Peru", code: "PER", dial: "+51" },
    { name: "Philippines", code: "PHL", dial: "+63" },
    { name: "Poland", code: "POL", dial: "+48" },
    { name: "Portugal", code: "PRT", dial: "+351" },
    { name: "Puerto Rico", code: "PRI", dial: "+1787" },
    { name: "Qatar", code: "QAT", dial: "+974" },
    { name: "Réunion", code: "REU", dial: "+262" },
    { name: "Romania", code: "ROU", dial: "+40" },
    { name: "Russia", code: "RUS", dial: "+7" },
    { name: "Rwanda", code: "RWA", dial: "+250" },
    { name: "Saint Helena", code: "SHN", dial: "+290" },
    { name: "Saint Kitts and Nevis", code: "KNA", dial: "+1869" },
    { name: "Saint Lucia", code: "LCA", dial: "+1758" },
    { name: "Saint Martin", code: "MAF", dial: "+590" },
    { name: "Saint Pierre and Miquelon", code: "SPM", dial: "+508" },
    { name: "Saint Vincent and the Grenadines", code: "VCT", dial: "+1784" },
    { name: "Samoa", code: "WSM", dial: "+685" },
    { name: "San Marino", code: "SMR", dial: "+378" },
    { name: "Sao Tome and Principe", code: "STP", dial: "+239" },
    { name: "Saudi Arabia", code: "SAU", dial: "+966" },
    { name: "Senegal", code: "SEN", dial: "+221" },
    { name: "Serbia", code: "SRB", dial: "+381" },
    { name: "Seychelles", code: "SYC", dial: "+248" },
    { name: "Sierra Leone", code: "SLE", dial: "+232" },
    { name: "Singapore", code: "SGP", dial: "+65" },
    { name: "Sint Maarten", code: "SXM", dial: "+1721" },
    { name: "Slovakia", code: "SVK", dial: "+421" },
    { name: "Slovenia", code: "SVN", dial: "+386" },
    { name: "Solomon Islands", code: "SLB", dial: "+677" },
    { name: "Somalia", code: "SOM", dial: "+252" },
    { name: "South Africa", code: "ZAF", dial: "+27" },
    { name: "South Korea", code: "KOR", dial: "+82" },
    { name: "South Sudan", code: "SSD", dial: "+211" },
    { name: "Spain", code: "ESP", dial: "+34" },
    { name: "Sri Lanka", code: "LKA", dial: "+94" },
    { name: "Sudan", code: "SDN", dial: "+249" },
    { name: "Suriname", code: "SUR", dial: "+597" },
    { name: "Sweden", code: "SWE", dial: "+46" },
    { name: "Switzerland", code: "CHE", dial: "+41" },
    { name: "Syria", code: "SYR", dial: "+963" },
    { name: "Taiwan", code: "TWN", dial: "+886" },
    { name: "Tajikistan", code: "TJK", dial: "+992" },
    { name: "Tanzania", code: "TZA", dial: "+255" },
    { name: "Thailand", code: "THA", dial: "+66" },
    { name: "Timor-Leste", code: "TLS", dial: "+670" },
    { name: "Togo", code: "TGO", dial: "+228" },
    { name: "Tokelau", code: "TKL", dial: "+690" },
    { name: "Tonga", code: "TON", dial: "+676" },
    { name: "Trinidad and Tobago", code: "TTO", dial: "+1868" },
    { name: "Tunisia", code: "TUN", dial: "+216" },
    { name: "Turkey", code: "TUR", dial: "+90" },
    { name: "Turkmenistan", code: "TKM", dial: "+993" },
    { name: "Turks and Caicos Islands", code: "TCA", dial: "+1649" },
    { name: "Tuvalu", code: "TUV", dial: "+688" },
    { name: "Uganda", code: "UGA", dial: "+256" },
    { name: "Ukraine", code: "UKR", dial: "+380" },
    { name: "United Arab Emirates", code: "ARE", dial: "+971" },
    { name: "United Kingdom", code: "GBR", dial: "+44" },
    { name: "United States", code: "USA", dial: "+1" },
    { name: "Uruguay", code: "URY", dial: "+598" },
    { name: "Uzbekistan", code: "UZB", dial: "+998" },
    { name: "Vanuatu", code: "VUT", dial: "+678" },
    { name: "Vatican City", code: "VAT", dial: "+379" },
    { name: "Venezuela", code: "VEN", dial: "+58" },
    { name: "Vietnam", code: "VNM", dial: "+84" },
    { name: "Wallis and Futuna", code: "WLF", dial: "+681" },
    { name: "Yemen", code: "YEM", dial: "+967" },
    { name: "Zambia", code: "ZMB", dial: "+260" },
    { name: "Zimbabwe", code: "ZWE", dial: "+263" }
];
